name: Gera relatorios
on:
  workflow_dispatch:
  schedule:
    - cron: "40 22 * * 1-5"

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Install cal and Lua
      run: sudo apt-get install -y ncal lua5.4
    - name: Clonar site
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'apstaiobeiras'
        repository: 'apstaiobeiras.github.io'

    - name: Clonar base
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'main'
        owner: 'apstaiobeiras'
        repository: 'Bases-de-dados'
        access-token: ${{ secrets.PAT }}

    - name: Salvar bases e gerar os scripts 
      run: |
        cd Bases-de-dados
        bash baixar-bases.sh
        cd relatorios
        lua5.4 producao-diaria.lua
        lua5.4 solicitacoes-agendadas.lua
        lua5.4 solicitacoes-excluidas.lua
        lua5.4 visita-domiciliar-acs.lua
        lua5.4 vitamina-a-100-mil.lua
        lua5.4 vacina-triplice.lua
        lua5.4 dispensacoes-por-unidade.lua
        lua5.4 pacientes-arbovirose.lua
        lua5.4 validacao-cadastros.lua
        lua5.4 completude-questionario-esus.lua
        lua5.4 farmacia.lua
        cd ..
        ls
        git config --global user.email "apstaiobeiras@gmail.com"
        git config --global user.name "Bot"
        git add .
        git commit -m "Atualização $(date +'%d/%m/%Y')" || true
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/apstaiobeiras/b.git || true
        git push || true

    - name: Publicar
      run: |
        cd apstaiobeiras.github.io
        git config --global user.email "apstaiobeiras@gmail.com"
        git config --global user.name "Bot"
        git add .
        git commit -m "Atualização $(date +'%d/%m/%Y')"
        git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/apstaiobeiras/apstaiobeiras.github.io.git
        git push


